# Generated by Django 5.0.6 on 2024-05-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_sys_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
