# Generated by Django 5.0.6 on 2024-05-31 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_sys_app', '0003_book_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='active',
        ),
    ]
