# Generated by Django 5.0.6 on 2024-06-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_sys_app', '0005_rename_publisher_book_score_book_image_and_more'),
    ]

    operations = [
    ]
