# Generated by Django 5.0.6 on 2024-06-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_sys_app', '0007_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userpassword',
            new_name='user_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_username',
        ),
        migrations.AddField(
            model_name='user',
            name='user_addr',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_contact',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_fullname',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_mail',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
